### ISSUE TITLE
Variants not displaying properly due to a Javascript error in the console.

### ISSUE THREAD

**Issue by afa32** [ebi-webcomponents/protvista-uniprot#25]
Hi,

We have noticed an issue with the display of the individual variants when expanding the variant section.

This can be seen in the [CodePen linked in the ReadMe](https://codepen.io/xwatkins/pen/rXpZXX).

Here, opening the variants section will show a different arrangement (and colors) compared to the corresponding page on the [uniprot website](https://www.uniprot.org/uniprot/P05067/protvista).

This is possibly due to a number of Javascript issues shown in the Javascript console on the codepen page.

We would appreciate your help and advice on how to get around this issue.

**Comment by afa32** [comment]
Just noticed that the codepen is pointing to an outdated version of the `protvista-uniprot` package from NPM.

Updating to the latest version fixed the issue.

**Comment by xwatkins** [comment]
Thanks for the heads up, I've updated the codepen.
